//import 'bootstrap';
//import 'bootstrap/scss/bootstrap.scss';
//import 'normalize.css/normalize.css';
import './sass/styles.scss';
import './js/menu.js';
import './js/cerrarredes.js';
import './js/fondoabout.js';
import './js/modals.js';
import 'animate.css/animate.css';
import Josh from 'joshjs';
const josh = new Josh();
